protected/models/Flowdocto.php
<?php

Yii::import('application.models._base.BaseFlowdocto');

class Flowdocto extends BaseFlowdocto
{
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}
}

protected/controllers/FlowdoctoController.php
<?php

class FlowdoctoController extends GxController {


	public function actionView($id) {
		EQuickDlgs::render('view',array('model'=>$this->loadModel($id,'Flowdocto')));
	}

	public function actionCreate() {
		$model = new Flowdocto;
                $this->performAjaxValidation($model);

		if (isset($_POST['Flowdocto'])) {
			$model->setAttributes($_POST['Flowdocto']);
                        $model->status=1;

			if ($model->save()) {
                            EQuickDlgs::checkDialogJsScript();
                            $this->redirect(array('admin'));
			}
		}

		EQuickDlgs::render('create',array('model'=>$model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Flowdocto');
                $this->performAjaxValidation($model);    

		if (isset($_POST['Flowdocto'])) {
			$model->setAttributes($_POST['Flowdocto']);

			if ($model->save()) {
                            EQuickDlgs::checkDialogJsScript();
                            $this->redirect(array('admin','id'=>$model->id));
			}
		}
                EQuickDlgs::render('update',array('model'=>$model));	
        }

	public function actionDelete($id) {

            $row= loadModel($id, 'Flowdocto')->delete();
            
            $cuantos = User::model()->count('status=1 and rolid=:rolid',array(':rolid'=>$id));

            if ($cuantos>0)
                throw new CHttpException(404, 'Rol tiene usuarios activos.');
            
            $row->active=0;
            $row->save();
            
            if(!isset($_GET['ajax']))
		$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));

	}

	public function actionIndex() {
		$model = new Flowdocto('search');
		$model->unsetAttributes();

		if (isset($_GET['Flowdocto']))
			$model->setAttributes($_GET['Flowdocto']);

		$this->render('admin', array(
			'model' => $model,
		));
	}

	public function actionAdmin() {
		$model = new Flowdocto('search');
		$model->unsetAttributes();

		if (isset($_GET['Flowdocto']))
			$model->setAttributes($_GET['Flowdocto']);

		$this->render('admin', array(
			'model' => $model,
		));
	}
        public function actionChild($id) {
                 $child_model = new FlowdoctoDetail("searchByParent");
                 $child_model->unsetAttributes();
                 EQuickDlgs::render('child',array(
                                    'model'=>$this->loadModel($id,'Flowdocto'),
                                    'child_model'=>$child_model,
                                    'parentId' => $id));
        }
        
        public function actions()
        {
            return array(
              'order' => array(
                  'class' => 'ext.OrderColumn.OrderAction',
                  'modelClass' => 'FlowdoctoDetail',
                  'pkName'  => 'id',
                  ),
            );
        }


}

protected/views/flowdocto/_form.php
<div class="wide form">


<?php $form = $this->beginWidget('GxActiveForm', array(
	'id' => 'flowdocto-form',
        'enableAjaxValidation'=>true,
        'clientOptions'=>array('validateOnSubmit'=>true,)
));
?>

	<p class="note">
		<?php echo Yii::t('app', 'Campos con '); ?> <span class="required">*</span> <?php echo Yii::t('app', 'son requeridos.'); ?>.
	</p>

	<?php /*echo $form->errorSummary($model); */?>
                <?php echo $form->hiddenField($model,'status'); ?>
		<div class="row">
		<?php echo $form->labelEx($model,'flowdescription'); ?>
		<?php echo $form->textField($model, 'flowdescription', array('maxlength' => 256,'size'=>50)); ?>
		<?php echo $form->error($model,'flowdescription'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'comments'); ?>
		<?php echo $form->textArea($model, 'comments',
                                            array('cols'=>50, 'rows'=>5)); ?>
		<?php echo $form->error($model,'comments'); ?>
		</div><!-- row -->

		<label><?php /*echo GxHtml::encode($model->getRelationLabel('flowdoctoDetails'));*/ ?></label>
		<?php /*echo $form->checkBoxList($model, 'flowdoctoDetails', GxHtml::encodeEx(GxHtml::listDataEx(FlowdoctoDetail::model()->findAllAttributes(null, true)), false, true));*/ ?>

<?php
echo GxHtml::submitButton(Yii::t('app', $model->isNewRecord ? 'Crear' : 'Grabar'));
$this->endWidget();
?>
</div><!-- form -->

protected/views/flowdocto/_search.php
<div class="wide form">

<?php $form = $this->beginWidget('GxActiveForm', array(
	'action' => Yii::app()->createUrl($this->route),
	'method' => 'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model, 'flowdescription'); ?>
		<?php echo $form->textField($model, 'flowdescription', array('maxlength' => 256,'size'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'comments'); ?>
		<?php echo $form->textArea($model, 'comments',
                                            array('cols'=>50, 'rows'=>5)); ?>
	</div>

	<div class="row buttons">
		<?php echo GxHtml::submitButton(Yii::t('app', 'Buscar')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/flowdocto/_view.php
<div class="view">

	<?php echo GxHtml::encode($data->getAttributeLabel('id')); ?>:
	<?php echo GxHtml::link(GxHtml::encode($data->id), array('view', 'id' => $data->id)); ?>
	<br />

	<?php echo GxHtml::encode($data->getAttributeLabel('flowdescription')); ?>:
	<?php echo GxHtml::encode($data->flowdescription); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('comments')); ?>:
	<?php echo GxHtml::encode($data->comments); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('status')); ?>:
	<?php echo GxHtml::encode($data->status); ?>
	<br />

</div>

protected/views/flowdocto/admin.php
<?php
Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('flowdocto-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1><?php echo Yii::t('app', 'Flujos de Trabajo'); ?></h1>

<p>
Opcionalmente, puede ingresar un operador (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
o <b>=</b>) al inicio de cada valor de búsqueda para especificar criterios personalizados.
</p>

<?php echo GxHtml::link(Yii::t('app', 'Búsqueda avanzada'), '#', array('class' => 'search-button')); ?>
<div class="search-form" style="display:none;">
<?php $this->renderPartial('_search', array(
	'model' => $model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id' => 'flowdocto-grid',
	'dataProvider' => $model->search(),
	'filter' => $model,
	'columns' => array(
		array('name'=>'id','filter'=>false,'htmlOptions'=>array('width'=>'60'),),
		'flowdescription',
		'comments',
		array(
                   'class'=>'EJuiDlgsColumn',
                    'template'=>'{view}{update}{delete}{detail}',
                    'htmlOptions'=>array('width'=>'80','style' => 'text-align: center;'),
                    //'viewButtonImageUrl'=>Yii::app()->baseUrl .'images/dialogview.png',
                    
                       'buttons'=>array(
                                'view' => array(
                                    'label'=> 'Ver detalle',
                                ),
                                'update' => array(
                                    'label'=> 'Editar',
                                 ),
                                'delete' => array(
                                   'label'=> 'Eliminar',
                                ),
                                'detail' => array(
                                    'label' => 'Detalle',
                                    'imageUrl'=>Yii::app()->baseUrl .'/images/detail.png',
                                    'url'=>'Yii::app()->createUrl("flowdocto/child", array("id"=>$data->primaryKey))',
                                )
                                
                   ),
                   'viewDialog'=>array(
                       'controllerRoute' => 'view', //=default
                       'actionParams' => array('id' => '$data->primaryKey'), //=default
                       'dialogTitle' => 'Detalle - Flujo de Trabajo',
                       'hideTitleBar' => true, 
                       'dialogWidth' => 600, //use the value from the dialog config
                       'dialogHeight' => 300,
                       'closeButtonText' => 'Cerrar'
                   ),

               //the attributes for the EFrameJuiDlg widget. use like the 'attributes' param from EQuickDlgs::iframeButton
                   'updateDialog'=>array(
                       'controllerRoute' => 'update', //=default
                       'actionParams' => array('id' => '$data->primaryKey'), //=default
                       'dialogTitle' => 'Modificar - Flujo de Trabajo',
                       'dialogWidth' => 600, //override the value from the dialog config
                       'dialogHeight' => 375,
                       'closeButtonText' => 'Cerrar'
                   ), 
               ),
	),
)); ?>

<?php 

EQuickDlgs::iframeButton(
    array(
        'controllerRoute' => 'create',
        'dialogTitle' => 'Agregar - Flujo de Trabajo',
        'dialogWidth' => 600,
        'dialogHeight' => 375,
        'openButtonText' => 'Agregar',
        'closeButtonText' => 'Cerrar',
        'closeOnAction' => true, //important to invoke the close action in the actionCreate
        'refreshGridId' => 'flowdocto-grid' //the grid with this id will be refreshed after closing
    )
);

?>

protected/views/flowdocto/child.php
    <h1><?php echo Yii::t('app', 'Detalle Flujo de Trabajo'); ?></h1>

        <?php $this->widget('zii.widgets.CDetailView', array(
                'data' => $model,
                'attributes' => array(
                    array('label' => 'Flujo de Trabajo', 
                        'value'=> $model->flowdescription
                        ,)
                ),
        )); ?>
        <?php
                $this->widget('zii.widgets.grid.CGridView', array(
                        'id'=>'child-grid',
                        'dataProvider'=>$child_model->searchByParent($parentId),
                        'columns'=>array(
                            //array('name'=>'id','htmlOptions'=>array('width'=>'60'),),
                            array(
                                'name'=>'Estado Actual',
                                'value'=>'GxHtml::valueEx($data->currentstatus)',
                                'filter'=>GxHtml::listDataEx(Status::model()->findAllAttributes(null, true,'', array('prompt' => Yii::t('app', 'Todos')))),
                            ),
                             array(
                                'name'=>'Nuevo Estado',
                                'value'=> function($data,$row) {
                                            return Status::model()->findByPk($data->newstatusid)->statusdescription;                                                   
                                } ,
                            ),
                            array(
                                'header' => '',
                                'name' => 'sort',
                                'htmlOptions'=>array('width'=>'20'),
                                'class' => 'ext.OrderColumn.OrderColumn',
                              ),
                           
                            array(
                                    'class'=>'EJuiDlgsColumn',
                                     'template'=>'{delete}',
                                     'htmlOptions'=>array('width'=>'10','style' => 'text-align: center;'),
                                        'buttons'=>array(
                                                 'delete' => array(
                                                    'label'=> 'Eliminar',
                                                     'url'=>'Yii::app()->createUrl("flowdoctoDetail/delete", array("id"=>$data->primaryKey))',
                                                 ),

                                    ),
                                ),
                            ),
                    ));
            
        ?>
<?php 

EQuickDlgs::iframeButton(
    array(
        'controllerRoute' => 'flowdoctoDetail/create/'.$parentId,
        'dialogTitle' => 'Agregar ',
        'dialogWidth' => 600,
        'dialogHeight' => 400,
        'openButtonText' => 'Agregar',
        'closeButtonText' => 'Cerrar',
        'closeOnAction' => true, //important to invoke the close action in the actionCreate
        'refreshGridId' => 'child-grid' //the grid with this id will be refreshed after closing
    )
);
?>
<?php    echo GxHtml::button('Regresar', array('submit'=>array('flowdocto/admin'))); ?>
<!-- http://www.yiiframework.com/forum/index.php/topic/32985-extension-quickdlgs/ -->

protected/views/flowdocto/create.php
<?php
$this->renderPartial('_form', array(
		'model' => $model,
		'buttons' => 'create'));
?>

protected/views/flowdocto/index.php
<?php

$this->breadcrumbs = array(
	Flowdocto::label(2),
	Yii::t('app', 'Index'),
);

$this->menu = array(
	array('label'=>Yii::t('app', 'Create') . ' ' . Flowdocto::label(), 'url' => array('create')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . Flowdocto::label(2), 'url' => array('admin')),
);
?>

<h1><?php echo GxHtml::encode(Flowdocto::label(2)); ?></h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); 

protected/views/flowdocto/update.php
<?php
$this->renderPartial('_form', array(
		'model' => $model));
?>

protected/views/flowdocto/view.php
<h1><?php echo Yii::t('app', 'Detalle')  ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data' => $model,
	'attributes' => array(
        'id',
        'flowdescription',
        'comments',
        'status',
	),
)); ?>

<h2><?php /*echo GxHtml::encode($model->getRelationLabel('flowdoctoDetails'));*/ ?></h2>
<?php /*
	echo GxHtml::openTag('ul');
	foreach($model->flowdoctoDetails as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('flowdoctoDetail/view', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');*/
?>